Repository appuio/component-openshift-upgrade-controller, pull requests merged in 2023-07, with the labels that each got.

#21 Add pre-configured alert silence hook
  class/defaults.yml
  component/main.jsonnet
  component/scripts/silence.sh
  component/silence.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_upgrade_silence.yaml
Labels: enhancement

#22 Adjust silence script to pass comment into jq as an argument
  component/scripts/silence.sh
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_upgrade_silence.yaml
Labels: bug

#23 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.3.1
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency

#24 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.3.2
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency

#26 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.4.0
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency
