Repository appuio/component-openshift-upgrade-controller, pull requests merged in 2023-08, with the labels that each got.

#27 Log more information when creating silences to debug issues with silences not expired
  component/scripts/silence.sh
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_upgrade_silence.yaml
Labels: change

#28 Fix existing silence match of the post-upgrade silence expiry
  component/scripts/silence.sh
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_upgrade_silence.yaml
Labels: bug

#29 FIx namespace of `managedupgrade.appuio.io.ClusterVersion`
  component/cluster-version.jsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/version.yaml
Labels: bug

#30 Remove default `baselineCapabilitySet` config
  component/cluster-version.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/version.yaml
Labels: change

#25 Update quay.io/appuio/oc Docker tag to v4.13
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_upgrade_silence.yaml
Labels: dependency
