Repository appuio/component-openshift-upgrade-controller, pull requests merged in 2023-06, with the labels that each got.

#7 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.1.2
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency

#8 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.2.0
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency

#11 Add "MaintenanceInProgress" Alert
  class/defaults.yml
  component/main.jsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/10_prometheusrule.yaml
Labels: enhancement

#13 Tune MaintenanceInProgress alert to not get interrupted on pod restart
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/10_prometheusrule.yaml
Labels: bug

#14 Fix incorrect YAML for aggregated roles
  component/rbac.jsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/30_rbac.yaml
Labels: bug

#16 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.3.0
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/rbac.authorization.k8s.io_v1_clusterrole_openshift-upgrade-controller-manager-role.yaml
Labels: dependency

#15 Component enhancements for `UpgradeJobHook`s
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/10_prometheusrule.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/20_upgradeconfigs.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/22_upgradejobhooks.yaml
Labels: enhancement

#17 Fix ArgoCD apply with `last-applied-configuration` annotation too big
  component/crds.jsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
Labels: bug

#18 ArgoCD sync options are annotations, not labels
  component/crds.jsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
Labels: bug

#20 Fix typo in generated `UpgradeJobHook` kind
  component/main.jsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/22_upgradejobhooks.yaml
Labels: bug
