Repository appuio/component-openshift-upgrade-controller, pull requests merged in 2024-06, with the labels that each got.

#55 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.7.1
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency

#56 Automate admin-ack
  class/defaults.yml
  component/admin-ack.libsonnet
  component/main.jsonnet
  component/scripts/admin-ack.sh
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_admin_ack.yaml
Labels: enhancement, bump:minor

#57 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.8.1
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradesuspensionwindows.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/rbac.authorization.k8s.io_v1_clusterrole_openshift-upgrade-controller-manager-role.yaml
Labels: dependency

#58 Allow managing `UpgradeSuspensionWindow` from the hierarchy
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/24_upgradesuspensionwindows.yaml
Labels: enhancement

#60 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.8.3
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency
