Repository appuio/component-openshift-upgrade-controller, pull requests merged in 2024-10, with the labels that each got.

#66 Add alert for paused machineconfigpools
  class/defaults.yml
  docs/modules/ROOT/pages/runbooks/PausedMachineConfigPool.adoc
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/10_prometheusrule.yaml
Labels: enhancement, bump:minor

#67 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.9.0
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradesuspensionwindows.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/rbac.authorization.k8s.io_v1_clusterrole_openshift-upgrade-controller-manager-role.yaml
Labels: dependency, bump:minor

#68 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.9.1
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency, bump:patch

#69 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.9.2
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_clusterversions.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradeconfigs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradesuspensionwindows.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency, bump:patch

#70 Update RBAC for maintenance silence job to be compatible with OpenShift 4.16
  component/silence.libsonnet
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/90_upgrade_silence.yaml
Labels: change, bump:patch
