Repository appuio/component-openshift-upgrade-controller, pull requests merged in 2025-02, with the labels that each got.

#77 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.11.1
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency, bump:patch

#79 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.11.2
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency, bump:patch

#80 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.12.0
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_nodeforcedrains.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobhooks.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apiextensions.k8s.io_v1_customresourcedefinition_upgradejobs.managedupgrade.appuio.io.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/rbac.authorization.k8s.io_v1_clusterrole_openshift-upgrade-controller-manager-role.yaml
Labels: dependency, bump:minor

#82 Update ghcr.io/appuio/openshift-upgrade-controller Docker tag to v0.12.1
  class/defaults.yml
  tests/golden/defaults/openshift-upgrade-controller/openshift-upgrade-controller/apps_v1_deployment_openshift-upgrade-controller-controller-manager.yaml
Labels: dependency, bump:patch

#83 OpenShift 4.17 requires `CREATE alertmanagers/api` for creating silences
  component/silence.libsonnet
Labels: bug
